### ISSUE TITLE
[Requirements] Feedback over requirements and HW-FW document 

### ISSUE THREAD

**Issue by ralcaide** [Sinapse-Energia/M2M-I2C-Development#1]
Please provide feedback based on the current HW-FW document and work to be dobe in order to adapt as best as possible the individual tasks to perform

**Comment by ralcaide** [comment]
@soporteHW , study the links available in the Readme and provide feedback like 
https://github.com/Sinapse-Energia/M2M-CAN-Development/issues/1

**Comment by soporteHW** [comment]
1) About I2C configuration function:

- baudRate:it is variable? Will it be measured in bit/s or Hz?
- address_list: Will this list only contain the reading addresses?

When a device or sensor is configured, where it saved? in a list? in a struct?

2) I understand that "i2c_address" is the writting address for each device or sensor. Is it not better to use a sensor name identifier as a parameter? If the device/sensor is previously defined or saved in a list or struct?

It is possible to have a list or struct that contains and identify all devices/sensors with its writting and reading addresses?

3) Read I2C Bus.
It's OK

**Comment by ralcaide** [comment]
I try to answer your questions:

1. 
a. Yes, it is a variable, the value can be one of the speeds available for I2C. We will use the same unit used in CAN in order to normalize
b. It depends of the protocol, and there it is where we need your feedback. In CAN it is only the reading addresses because is what need CAN. Maybe in I2C we need something else.
c. The goal is to have a config function that permit the configuration of any I2C without limitations. 

2. 
a. I think not. If you do like that is not generic and the function depends on the config definitions. The goal is to have something that works always. Normally, your idea should be developed in a superior layer, not in the L1 (generic)
b. Also, related to I2C we require your feedback. In CAN makes sense to  provide the writing address because in the config could be provided only the broadcast address in order to listen everything and then in the writing it is provided only the concrete address of a device
c. About the list: I don't know if it is necessary / possible. It depends of the protocol. I will try to read a bit more and we can talk about that

**Comment by soporteHW** [comment]
Doubt about I2C_config() function:

I2C standard protocol use 7 bit for addressing mode, but it has available 10 bit addressing mode option. This last mode is rarely used, Do you think it is necessary to include as param in the function?

**Comment by soporteHW** [comment]
I think it is necessary to include one function to read specific internal register in a sensor/device, i.e, the functions will be:

1. I2C_config() -> initialize and configure I2C parameters.
2. I2C_Write_Msg() -> initialize and configure internal registers in a specific sensor/device
3. I2C_Read_Msg() -> read a internal register in a specific sensor/device
4. I2C_Get_Value() -> captures a value left by a sensor/device on the I2C bus

**Comment by soporteHW** [comment]
Some comments:

- Unlike CAN protocol, I2C hasn't continuous data transfer, i.e., a sensor only puts data on I2C bus when it has received a previous request. Maybe, it's not neccessary to implement queue function.
- The returned values by a sensor/device will have variable length. it is mandatory to think properly about the implementation of these cases.

**Comment by ralcaide** [comment]
To be done in outsourcing
